CREATE TABLE `personas` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `nombre` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `ciudad` varchar(100) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Hannah","ipsum@Cras.org","Mauritius"),("Lawrence","libero.nec.ligula@natoquepenatibus.net","Botswana"),("Elliott","fermentum.metus.Aenean@nisi.co.uk","Macedonia"),("Keely","dolor@magnaPhasellus.edu","Croatia"),("Regan","semper.egestas.urna@pretiumnequeMorbi.ca","Bangladesh"),("Colton","eleifend.vitae@vitaeposuereat.ca","Egypt"),("Valentine","sit.amet@venenatis.co.uk","Falkland Islands"),("Veda","quis@aultricies.edu","British Indian Ocean Territory"),("Cain","vitae.sodales@mattis.org","Anguilla"),("Bernard","mus.Donec@justo.co.uk","Congo (Brazzaville)");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Ishmael","ornare@accumsannequeet.ca","Mauritius"),("Brendan","tempus@sedest.org","Mexico"),("Harriet","rhoncus.id.mollis@mollisDuissit.net","Iraq"),("Amaya","pede.Praesent@viverraDonec.edu","Egypt"),("Ariana","parturient.montes.nascetur@euismod.org","Burkina Faso"),("Nomlanga","venenatis.lacus@venenatisvel.com","Bahamas"),("Melvin","Vivamus.nibh.dolor@feliseget.edu","British Indian Ocean Territory"),("Clinton","ligula.consectetuer.rhoncus@egetvariusultrices.edu","Montserrat"),("Maxine","ac@orci.com","Gabon"),("Walter","ridiculus@sapienmolestieorci.org","Azerbaijan");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Ralph","vel.pede@loremlorem.co.uk","Chile"),("Ronan","dolor@mipede.com","Madagascar"),("Ila","vitae@scelerisque.org","Solomon Islands"),("Shelley","eu@tempusloremfringilla.com","Anguilla"),("Hadassah","lacus.vestibulum@gravidamauris.org","Bonaire, Sint Eustatius and Saba"),("Zenaida","vestibulum@Vestibulumaccumsanneque.com","El Salvador"),("Neve","vel.est@aceleifendvitae.org","Saint Kitts and Nevis"),("Abdul","eu.enim.Etiam@etlibero.edu","Cape Verde"),("Tatiana","dui.quis@imperdietnon.co.uk","United States"),("Garth","Aliquam@variusNamporttitor.org","Wallis and Futuna");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Guinevere","at.lacus@morbitristique.co.uk","Argentina"),("Hakeem","ipsum@lectussit.net","Bosnia and Herzegovina"),("Simon","diam@Phasellus.com","Maldives"),("Malik","amet.dapibus.id@nec.ca","Moldova"),("Kelly","ut.molestie.in@varius.co.uk","Ghana"),("Kimberley","magnis.dis.parturient@disparturient.net","Guatemala"),("Shana","Proin.mi.Aliquam@mitemporlorem.ca","Thailand"),("Lane","sociis.natoque@lacusUtnec.net","Sri Lanka"),("Erasmus","egestas.nunc.sed@lectus.ca","Chile"),("Tanya","convallis@nonlorem.edu","Cape Verde");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Jerome","blandit.congue@diamnuncullamcorper.ca","Armenia"),("Valentine","sit.amet@egestasrhoncus.co.uk","Puerto Rico"),("Michael","orci@faucibusidlibero.co.uk","Pakistan"),("Cade","pede.ultrices@Morbi.edu","Belgium"),("Uta","adipiscing@ligulaAliquam.com","Andorra"),("Tatum","magna.et.ipsum@justoPraesentluctus.net","French Guiana"),("Basia","et.nunc@Phasellus.org","Swaziland"),("Leigh","iaculis.enim.sit@quam.com","Norfolk Island"),("Aurora","Curabitur.egestas.nunc@luctusipsumleo.org","Latvia"),("Nomlanga","Nulla@Aliquam.com","Zimbabwe");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Lewis","mi.eleifend.egestas@amet.ca","Guinea"),("Dale","lectus.justo.eu@lacusQuisque.co.uk","Russian Federation"),("Leslie","enim@bibendum.net","Tokelau"),("Iona","nisl.Quisque@ridiculusmusProin.com","Curaçao"),("Judith","ligula.Nullam@sem.net","Zimbabwe"),("Graiden","nec.ante.blandit@ProindolorNulla.co.uk","Thailand"),("Gay","orci.Ut.semper@purusmaurisa.net","Wallis and Futuna"),("Emmanuel","tincidunt@libero.edu","Virgin Islands, British"),("Daquan","lobortis.Class.aptent@Aeneaneget.com","Aruba"),("Mia","molestie.dapibus.ligula@necluctusfelis.net","Cameroon");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Kylan","Lorem.ipsum.dolor@vitae.ca","China"),("Tyler","Nullam.lobortis@Proinvel.ca","Argentina"),("Daryl","vel.nisl@vulputateullamcorpermagna.org","Bermuda"),("Amir","vestibulum@Nam.co.uk","Norway"),("Ronan","Quisque@Sed.ca","Saint Helena, Ascension and Tristan da Cunha"),("Brenden","justo.Praesent.luctus@nuncnulla.org","Tajikistan"),("Rashad","ac.libero@maurisrhoncus.ca","Malaysia"),("Kessie","Fusce.mollis@risus.co.uk","Palau"),("Mira","mattis@in.co.uk","Mozambique"),("Fritz","Integer.in@aptenttacitisociosqu.co.uk","Sierra Leone");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Shellie","dolor.elit@molestie.edu","Timor-Leste"),("Henry","eget.varius@inconsectetueripsum.edu","Honduras"),("Ahmed","Curae.Phasellus@Duis.edu","Honduras"),("Debra","ac.fermentum@Nam.co.uk","Pitcairn Islands"),("Cassidy","enim@velitSedmalesuada.co.uk","Malawi"),("Aimee","venenatis.vel@adipiscinglacus.com","Guernsey"),("Michael","mattis@convallis.edu","Algeria"),("Davis","Nullam.ut.nisi@luctus.ca","Madagascar"),("Sierra","eu.nibh.vulputate@et.ca","Aruba"),("Lev","eleifend.vitae@metus.co.uk","Sri Lanka");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Chancellor","porttitor.tellus@Quisqueliberolacus.edu","Gibraltar"),("Solomon","semper@Vivamusmolestiedapibus.org","Christmas Island"),("Candice","Nulla.eu.neque@tinciduntnuncac.com","Hong Kong"),("Jolene","nec.leo.Morbi@ullamcorperDuis.net","Chad"),("Ciaran","non.feugiat.nec@felisullamcorper.co.uk","Costa Rica"),("Carla","turpis.non@mollis.com","United States"),("Anjolie","massa.lobortis.ultrices@lectuspede.net","Pakistan"),("Dillon","nec@velitSedmalesuada.ca","United Arab Emirates"),("Anastasia","risus.Morbi.metus@liberoat.org","Central African Republic"),("Leo","felis.Nulla@metusvitaevelit.net","Guinea-Bissau");
INSERT INTO `personas` (`nombre`,`email`,`ciudad`) VALUES ("Hamish","facilisis.eget@Fuscemi.com","Kazakhstan"),("Trevor","mauris.aliquam@Quisquefringillaeuismod.net","French Southern Territories"),("Amir","metus.Aliquam.erat@Maecenaslibero.edu","Belgium"),("Wendy","Aliquam.ultrices@tinciduntorci.com","Niue"),("Fay","diam.Sed.diam@Proinvelit.com","Morocco"),("Jelani","nibh@indolor.org","Netherlands"),("Kenneth","magnis.dis@et.ca","Ukraine"),("Deanna","Curabitur.dictum@metusInnec.edu","Serbia"),("Basia","semper@orcilobortis.edu","Norfolk Island"),("Dacey","dui.Fusce@Pellentesquehabitant.ca","Brazil");
